"""
CumulusCI tasks for the Revenue Cloud Portal (rlm-webapp) feature flag.

Tasks:
  ConfigurePortalWebapp  — queries the RLM Portal External Client App's Consumer Key
                           from the org (via Tooling API) and writes
                           rlm-webapp/.env.local so Vite picks up the correct
                           instanceUrl and clientId automatically.

Usage:
  cci task run configure_portal_webapp --org <alias>

The task is a no-op when portal=false (enforced by the when: condition in the
prepare_portal flow).  Run it standalone after creating a new org or after the
External Client App is re-deployed.
"""

import os

import requests

try:
    from cumulusci.core.tasks import BaseTask
    from cumulusci.core.exceptions import TaskOptionsError
except ImportError:
    BaseTask = object
    TaskOptionsError = Exception


class ConfigurePortalWebapp(BaseTask):
    """
    Reads the RLM Portal External Client App's Consumer Key from the org and writes
    rlm-webapp/.env.local with VITE_SF_INSTANCE_URL and VITE_SF_CLIENT_ID.

    Vite automatically loads .env.local at dev-server startup, so the webapp
    will connect to the correct org without any manual config editing.

    The .env.local file is gitignored — it is never committed.
    """

    task_docs = """
    After ``deploy_portal_connected_app`` has deployed the RLM Portal External Client
    App metadata, this task:

    1. Queries the ExternalClientApplication Tooling API object for the Consumer Key
       (falls back to ConnectedApplication for legacy orgs).
    2. Resolves the org's instance URL from org_config.
    3. Writes ``rlm-webapp/.env.local`` with::

         VITE_SF_INSTANCE_URL=https://<org>.my.salesforce.com
         VITE_SF_CLIENT_ID=<consumerKey>

    The webapp's ``src/config.js`` reads these env vars at build/dev time via
    ``import.meta.env``, falling back to the hardcoded values for manual setups.
    """

    task_options = {
        "connected_app_name": {
            "description": (
                "Label of the External Client App (or Connected App, for legacy orgs) "
                "to look up in the org (default: 'RLM Portal')."
            ),
            "required": False,
        },
        "env_file_path": {
            "description": (
                "Relative path from the repo root to the .env.local file to write "
                "(default: 'rlm-webapp/.env.local')."
            ),
            "required": False,
        },
        "extra_callback_urls": {
            "description": (
                "Comma-separated list of additional callback URLs to add to the "
                "External Client App (e.g. your Heroku URL). These are appended to the "
                "existing callbackUrl list via a PATCH on the ECA Global OAuth Settings "
                "record. Optional."
            ),
            "required": False,
        },
    }

    def _run_task(self):
        app_name = self.options.get("connected_app_name", "RLM Portal")
        env_path = self.options.get("env_file_path", "rlm-webapp/.env.local")
        extra_urls = self.options.get("extra_callback_urls", "")

        access_token = self.org_config.access_token
        instance_url = self.org_config.instance_url
        api_version = (
            getattr(self.org_config, "api_version", None)
            or getattr(self.project_config, "project__package__api_version", "66.0")
        )

        headers = {
            "Authorization": f"Bearer {access_token}",
            "Content-Type": "application/json",
        }

        # ── 1. Query ConsumerKey via Tooling API ─────────────────────────────
        # Try ExternalClientApplication first (Spring '24+ ECA approach),
        # then fall back to ConnectedApplication (legacy Connected Apps).
        consumer_key, app_id, app_type = self._get_consumer_key(
            instance_url, api_version, headers, app_name
        )

        # ── 2. Optionally patch extra callback URLs ───────────────────────────
        if extra_urls.strip():
            new_urls = [u.strip() for u in extra_urls.split(",") if u.strip()]
            self._add_callback_urls(
                instance_url, api_version, headers, app_id, new_urls, app_type
            )

        # ── 3. Write rlm-webapp/.env.local ───────────────────────────────────
        repo_root = self.project_config.repo_root
        abs_env_path = os.path.join(repo_root, env_path)
        os.makedirs(os.path.dirname(abs_env_path), exist_ok=True)

        env_content = (
            "# Revenue Cloud Portal — auto-generated by CCI configure_portal_webapp\n"
            "# Do NOT commit this file — it contains org-specific values.\n"
            "# Re-run `cci task run configure_portal_webapp --org <alias>` after org changes.\n"
            f"VITE_SF_INSTANCE_URL={instance_url}\n"
            f"VITE_SF_CLIENT_ID={consumer_key}\n"
        )

        with open(abs_env_path, "w", encoding="utf-8") as f:
            f.write(env_content)

        self.logger.info(f"Wrote {env_path} with instance URL and Client ID.")
        self.logger.info(
            "Start (or restart) the Vite dev server to pick up the new values:\n"
            "  cd rlm-webapp && npm run dev"
        )

    def _get_consumer_key(self, instance_url, api_version, headers, app_name):
        """
        Query Consumer Key for the named app.

        Tries ExternalClientApplication first (ECA, Spring '24+), then falls back
        to ConnectedApplication (legacy Connected Apps).  Returns (consumer_key, record_id, app_type).
        """
        tooling_url = f"{instance_url}/services/data/v{api_version}/tooling/query"
        app_name_escaped = app_name.replace("'", "\\'")

        # ── Try External Client App first ─────────────────────────────────────
        eca_soql = (
            f"SELECT Id, Label, ConsumerKey FROM ExternalClientApplication "
            f"WHERE Label = '{app_name_escaped}' LIMIT 1"
        )
        self.logger.info(
            f"Querying Tooling API for External Client App '{app_name}' (ECA)..."
        )
        eca_resp = requests.get(tooling_url, headers=headers, params={"q": eca_soql})

        if eca_resp.ok:
            eca_result = eca_resp.json()
            if eca_result.get("totalSize", 0) > 0:
                record = eca_result["records"][0]
                consumer_key = record["ConsumerKey"]
                self.logger.info(
                    f"Found ECA '{app_name}' — ConsumerKey: {consumer_key[:12]}..."
                )
                return consumer_key, record["Id"], "eca"
            self.logger.info(
                "ECA query returned 0 records — falling back to ConnectedApplication."
            )
        else:
            self.logger.info(
                f"ECA Tooling query failed ({eca_resp.status_code}) — "
                "falling back to ConnectedApplication."
            )

        # ── Fall back to legacy Connected App ─────────────────────────────────
        ca_soql = (
            f"SELECT Id, Name, ConsumerKey FROM ConnectedApplication "
            f"WHERE Name = '{app_name_escaped}' LIMIT 1"
        )
        self.logger.info(
            f"Querying Tooling API for Connected App '{app_name}' (legacy)..."
        )
        ca_resp = requests.get(tooling_url, headers=headers, params={"q": ca_soql})
        ca_resp.raise_for_status()
        ca_result = ca_resp.json()

        if ca_result.get("totalSize", 0) == 0:
            raise TaskOptionsError(
                f"App '{app_name}' not found as an External Client App or Connected App. "
                "Run deploy_portal_connected_app first, then wait ~2 minutes for "
                "Salesforce to activate it before retrying."
            )

        record = ca_result["records"][0]
        consumer_key = record["ConsumerKey"]
        self.logger.info(
            f"Found Connected App '{app_name}' — ConsumerKey: {consumer_key[:12]}..."
        )
        return consumer_key, record["Id"], "connected_app"

    def _add_callback_urls(
        self, instance_url, api_version, headers, app_id, new_urls, app_type
    ):
        """
        Append new_urls to the app's callbackUrl list via Tooling API PATCH.
        Handles both ECA (ExtlClntAppGlobalOauthSettings) and legacy Connected Apps.
        Only adds URLs that are not already present.
        """
        tooling_base = f"{instance_url}/services/data/v{api_version}/tooling"

        if app_type == "eca":
            # For ECAs, callback URL lives on the ExtlClntAppGlobalOauthSettings record.
            # Query by the ECA Id to find the associated global settings record.
            glbl_soql = (
                f"SELECT Id, CallbackUrl FROM ExtlClntAppGlobalOauthSettings "
                f"WHERE ExternalClientApplicationId = '{app_id}' LIMIT 1"
            )
            glbl_resp = requests.get(
                f"{tooling_base}/query",
                headers=headers,
                params={"q": glbl_soql},
            )
            glbl_resp.raise_for_status()
            glbl_result = glbl_resp.json()

            if glbl_result.get("totalSize", 0) == 0:
                self.logger.warning(
                    "Could not find ExtlClntAppGlobalOauthSettings — skipping URL patch."
                )
                return

            glbl_record = glbl_result["records"][0]
            existing_raw = glbl_record.get("CallbackUrl", "")
            existing = [u.strip() for u in existing_raw.splitlines() if u.strip()]
            to_add = [u for u in new_urls if u not in existing]

            if not to_add:
                self.logger.info(
                    "All extra callback URLs already present — skipping patch."
                )
                return

            updated_str = "\n".join(existing + to_add)
            patch_resp = requests.patch(
                f"{tooling_base}/sobjects/ExtlClntAppGlobalOauthSettings/{glbl_record['Id']}",
                headers=headers,
                json={"CallbackUrl": updated_str},
            )
        else:
            # Legacy Connected App — callback URL is in oauthConfig.callbackUrl
            detail_resp = requests.get(
                f"{tooling_base}/sobjects/ConnectedApplication/{app_id}",
                headers=headers,
            )
            detail_resp.raise_for_status()
            detail = detail_resp.json()

            existing_raw = detail.get("oauthConfig", {}).get("callbackUrl", "")
            existing = [u.strip() for u in existing_raw.splitlines() if u.strip()]
            to_add = [u for u in new_urls if u not in existing]

            if not to_add:
                self.logger.info(
                    "All extra callback URLs already present — skipping patch."
                )
                return

            updated_str = "\n".join(existing + to_add)
            patch_resp = requests.patch(
                f"{tooling_base}/sobjects/ConnectedApplication/{app_id}",
                headers=headers,
                json={"oauthConfig": {"callbackUrl": updated_str}},
            )

        if patch_resp.status_code == 204:
            self.logger.info(f"Added callback URLs: {', '.join(to_add)}")
        else:
            try:
                err = patch_resp.json()
            except Exception:
                err = patch_resp.text
            self.logger.warning(f"Could not patch callback URLs: {err}")
