"""Offline negative fixtures for public skill discovery and navigation gates.

Run with Python 3.10+; no org, network, PyYAML, or agent client required.
"""
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "scripts" / "ai"))
import analyze_agent_tooling as analyzer
import pr_gate


class LaunchChecks(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self.tmp.cleanup)
        self.root = Path(self.tmp.name)
        self.skill = self.root / ".cursor/skills/cci-orchestration/SKILL.md"
        self.metadata = "---\nname: cci-orchestration\ndescription: >-\n  Work with tasks.\n  Use for orchestration.\n---\n"
        for name in analyzer.REQUIRED_FILES + analyzer.BASELINE_EXTRA_FILES + list(analyzer.NAVIGATION_ROOTS):
            if name != "CLAUDE.md":
                self.write(name, "# Guide\n")
        self.write("scripts/ai/analyze_agent_tooling.py", (REPO / "scripts/ai/analyze_agent_tooling.py").read_text())
        self.write("scripts/ai/generate_cci_reference.py", '# PyYAML\n')
        self.write("scripts/ai/skill_manifest.py", '# PyYAML minimal fallback\n')
        self.write("scripts/ai/README.md", "Baseline static checks; full generated-reference checks\n")
        self.write(".claude/skill-manifest.yml", "manifest_version: 2\nfoundations:\npmos:\nskills:\ngrounding:\n")
        refs = []
        for name in analyzer.GENERATED_CCI_REFERENCE_FILES:
            self.write(name, "Auto-generated by scripts/ai/generate_cci_reference.py\n")
            refs.append(f"`{Path(name).name}`")
        self.skill.write_text(self.metadata + "\n".join(refs))
        self.write(".cursor/rules/example.mdc", "# Rule\n")
        self.write(".cursor/skills/README.md", "## File-Specific Rules\n\n| Rule | Triggers On | Equivalent Skill |\n|---|---|---|\n| `example.mdc` | `*.py` | `cci-orchestration/SKILL.md` |\n")
        for folder in (".agents/skills", ".claude/skills"):
            (self.root / folder).mkdir(parents=True)
            (self.root / folder / "cci-orchestration").symlink_to("../../.cursor/skills/cci-orchestration", target_is_directory=True)
        (self.root / "CLAUDE.md").symlink_to("AGENTS.md")
        self.git("init", "-q")
        self.git("add", ".")

    def write(self, path, text):
        p = self.root / path
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(text)
        return p

    def git(self, *args):
        return subprocess.run(["git", "-c", "core.fsmonitor=false", "-C", str(self.root), *args],
                              capture_output=True, text=True, check=True)

    def cli(self):
        return subprocess.run([sys.executable, "-S", str(REPO / "scripts/ai/analyze_agent_tooling.py"),
                               "--repo-root", str(self.root), "check"], capture_output=True, text=True)

    def test_clean_baseline_without_site_packages(self):
        result = self.cli()
        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        for label in ("skill discovery metadata", "native skill links", "root instruction budget", "skill navigation links"):
            self.assertIn("[PASS] " + label, result.stdout)

    def test_missing_and_invalid_metadata(self):
        cases = ["# Missing", "---\nname: cci-orchestration\ndescription: Short\n  " + "x" * 1030 + "\n---", "---\nname: cci-orchestration\n---", "---\nname: wrong\ndescription: Good\n---",
                 "---\nname: cci-orchestration\nname: cci-orchestration\ndescription: Good\n---"]
        cases += [f"---\nname: cci-orchestration\ndescription: {v}\n---" for v in
                  ("", "# comment", "true", "42", "0xFF", ".nan", ".5", "[]", "{key: value}", "*alias", '""', '"unterminated', '"' + 'x' * 1025 + '"')]
        for content in cases:
            with self.subTest(content=content[:70]):
                self.skill.write_text(content)
                result = analyzer.check_skill_discovery_metadata(self.root)
                self.assertFalse(result.ok, result.detail)
                self.assertIn("SKILL.md", result.detail)
        self.skill.unlink()
        self.assertFalse(analyzer.check_skill_discovery_metadata(self.root).ok)

    def test_yaml_plain_indicator_boundaries(self):
        invalid = ["- invalid", "? invalid", ": invalid", "-", "?", ":",
                   ",invalid", "]invalid", "}invalid", "%invalid", "@invalid", "`invalid",
                   "-\tinvalid", "?\tinvalid", ":\tinvalid", "trailing:", "key:\tvalue"]
        for value in invalid:
            with self.subTest(value=value):
                self.skill.write_text(f"---\nname: cci-orchestration\ndescription: {value}\n---\n")
                self.assertFalse(analyzer.check_skill_discovery_metadata(self.root).ok)
        for value in ("-valid", "?valid", ":valid", "https://example.com", "Use foo:bar", '"- quoted"', "'@quoted'"):
            with self.subTest(value=value):
                self.skill.write_text(f"---\nname: cci-orchestration\ndescription: {value}\n---\n")
                self.assertTrue(analyzer.check_skill_discovery_metadata(self.root).ok)
        self.skill.write_text("---\nname: cci-orchestration\ndescription: - invalid\n---\n")
        result = self.cli()
        self.assertEqual(result.returncode, 1)
        self.assertIn("[FAIL] skill discovery metadata", result.stdout)

    def test_equivalent_required_keys_are_duplicates(self):
        for key in ("name", "description"):
            for spelling in (key + " ", key + "\t", f"'{key}'", f'"{key}"',
                             '"\\u%04x%s"' % (ord(key[0]), key[1:])):
                with self.subTest(key=key, spelling=spelling):
                    self.skill.write_text(self.metadata.rsplit("---", 1)[0] + f"{spelling}: wrong\n---\n")
                    self.assertFalse(analyzer.check_skill_discovery_metadata(self.root).ok)
        self.assertEqual(self.cli().returncode, 1)
        for field in ('? name\n: wrong', '!!str name: wrong', '&key name: wrong',
                      '"na\\x6de": wrong'):
            with self.subTest(unsupported_key=field):
                self.skill.write_text(self.metadata.rsplit("---", 1)[0] + field + "\n---\n")
                self.assertFalse(analyzer.check_skill_discovery_metadata(self.root).ok)
        for key in ("name", "description"):
            for spelling in (key + " ", key + "\t", f"'{key}'", f'"{key}"'):
                self.skill.write_text(self.metadata.replace(key + ":", spelling + ":"))
                self.assertTrue(analyzer.check_skill_discovery_metadata(self.root).ok)

    def test_timestamp_values_require_string_quoting(self):
        timestamps = ("2026-09-16", "2026-09-16T04:35:06Z", "2026-09-16t04:35:06.12-05:00",
                      "2026-9-6 4:35:06 +5:30", "2026-09-16 04:35:06", "2026-09-16\t04:35:06.1 Z")
        for value in timestamps:
            with self.subTest(value=value):
                self.skill.write_text(f"---\nname: cci-orchestration\ndescription: {value}\n---\n")
                self.assertFalse(analyzer.check_skill_discovery_metadata(self.root).ok)
                self.skill.write_text(f"---\nname: cci-orchestration\ndescription: '{value}'\n---\n")
                self.assertTrue(analyzer.check_skill_discovery_metadata(self.root).ok)
        self.skill.write_text("---\nname: cci-orchestration\ndescription: 2026-09-16T04:35:06Z\n---\n")
        self.assertEqual(self.cli().returncode, 1)
        for value in ("Meet at 2026-09-16T04:35:06Z", "2026-09-16 release guide"):
            self.skill.write_text(f"---\nname: cci-orchestration\ndescription: {value}\n---\n")
            self.assertTrue(analyzer.check_skill_discovery_metadata(self.root).ok)

    def test_yaml_single_letter_booleans_require_quotes(self):
        for value in ('y', 'Y', 'n', 'N'):
            with self.subTest(value=value):
                self.skill.write_text(f'---\nname: cci-orchestration\ndescription: {value}\n---\n')
                self.assertFalse(analyzer.check_skill_discovery_metadata(self.root).ok)
                self.assertEqual(self.cli().returncode, 1)
                self.skill.write_text(f"---\nname: cci-orchestration\ndescription: '{value}'\n---\n")
                self.assertTrue(analyzer.check_skill_discovery_metadata(self.root).ok)

    def test_supported_metadata_scalars(self):
        for value in ('Plain task description', '"Quoted task description"', "'A user''s task'", '|-\n  Line one.\n  Line two.', '>\n  Folded\n  text.'):
            with self.subTest(value=value):
                self.skill.write_text(f"---\nname: cci-orchestration\ndescription: {value}\n---\n")
                self.assertTrue(analyzer.check_skill_discovery_metadata(self.root).ok)

    def test_block_chomping_and_length(self):
        for marker, tail in ((">-", ""), (">", "\n"), (">+", "\n\n"), ("|-", ""), ("|", "\n"), ("|+", "\n\n")):
            fm = f"description: {marker}\n  Text\n\n"
            self.assertEqual(analyzer._discovery_scalar(fm, "description"), "Text" + tail)
        for marker, expected in ((">-", True), (">", False), ("|+", False)):
            self.skill.write_text(f"---\nname: cci-orchestration\ndescription: {marker}\n  " + "x" * 1024 + "\n---\n")
            self.assertEqual(analyzer.check_skill_discovery_metadata(self.root).ok, expected)

    def test_empty_inventory_is_not_success(self):
        empty = self.root / "empty"
        empty.mkdir()
        self.assertFalse(analyzer.check_skill_discovery_metadata(empty).ok)
        self.assertFalse(analyzer.check_native_skill_links(empty).ok)

    def test_budget_counts_bytes_and_boundary(self):
        p = self.root / "AGENTS.md"
        for text, expected in [("a" * 25000, True), ("a" * 25001, False), ("é" * 12501, False), ("", False)]:
            p.write_text(text)
            self.assertEqual(analyzer.check_instruction_budget(self.root).ok, expected)
        p.unlink()
        self.assertFalse(analyzer.check_instruction_budget(self.root).ok)

    def test_native_link_missing_wrong_copied_and_untracked(self):
        p = self.root / ".agents/skills/cci-orchestration"
        p.unlink()
        self.assertFalse(analyzer.check_native_skill_links(self.root).ok)
        p.symlink_to("../../.cursor/skills/missing")
        self.assertFalse(analyzer.check_native_skill_links(self.root).ok)
        p.unlink()
        p.mkdir()
        (p / "SKILL.md").write_text(self.metadata)
        self.assertFalse(analyzer.check_native_skill_links(self.root).ok)
        (p / "SKILL.md").unlink()
        p.rmdir()
        p.symlink_to("../../.cursor/skills/cci-orchestration")
        self.git("rm", "--cached", ".agents/skills/cci-orchestration")
        self.assertFalse(analyzer.check_native_skill_links(self.root).ok)

    def test_native_extra_and_root_adapter(self):
        p = self.root / ".claude/skills/unexpected"
        p.symlink_to("../../.cursor/skills/cci-orchestration")
        self.assertFalse(analyzer.check_native_skill_links(self.root).ok)
        p.unlink()
        p = self.root / "CLAUDE.md"
        p.unlink()
        p.symlink_to("README.md")
        self.assertFalse(analyzer.check_native_skill_links(self.root).ok)

    def test_local_link_variants_and_deleted_target(self):
        self.write("docs/a b.md", "# Reference")
        self.write("docs/one(two).md", "# Reference")
        self.write("README.md", '[inline](docs/a%20b.md#heading) [angle](<docs/a b.md> "title")\n'
                   '[balanced](docs/one(two).md)\n[ref]: docs/a%20b.md "title"\n')
        self.assertTrue(analyzer.check_skill_navigation_links(self.root).ok)
        (self.root / "docs/a b.md").unlink()
        result = analyzer.check_skill_navigation_links(self.root)
        self.assertFalse(result.ok)
        self.assertIn("README.md", result.detail)
        self.assertIn("docs/a%20b.md", result.detail)

    def test_escaped_angle_destination_target_deletion(self):
        cases = ((r'docs/a b\>c.md', 'docs/a b>c.md'),
                 (r'docs/a b\<c.md', 'docs/a b<c.md'),
                 (r'docs/a b\>', 'docs/a b>'),
                 (r'docs/a b\\c.md', 'docs/a b\\c.md'))
        for escaped, filename in cases:
            for content in (f'[guide](<{escaped}>)', f'![image](<{escaped}>)',
                            f'[guide]({escaped.replace(" ", "%20")})',
                            f'[ref]: <{escaped}>\n\n[guide][ref]'):
                with self.subTest(content=content):
                    target = self.write(filename, '# Guide')
                    self.write('README.md', content)
                    self.assertTrue(analyzer.check_skill_navigation_links(self.root).ok)
                    target.unlink()
                    self.assertFalse(analyzer.check_skill_navigation_links(self.root).ok)
        self.write('README.md', r'[guide](<docs/a b\>c.md>)')
        self.assertEqual(self.cli().returncode, 1)

    def test_second_link_and_reference_definition_fail(self):
        for content in ('[ok](AGENTS.md "title") [bad](missing.md)', '[bad]: missing.md', '![image](missing.png)', '[bad](docs/a\\ b.md)'):
            self.write("README.md", content)
            self.assertFalse(analyzer.check_skill_navigation_links(self.root).ok, content)

    def test_link_openers_and_escape_parity(self):
        nonlinks = [r"\[literal](missing.md)", "literal](missing.md)",
                    r"\![literal\](missing.md)", r"\[ref]: missing.md",
                    r"[ref\]: missing.md", "[outer [inner](AGENTS.md)](missing.md)",
                    "[literal\n\ntext](missing.md)"]
        for content in nonlinks:
            with self.subTest(nonlink=content):
                self.write("README.md", content)
                self.assertTrue(analyzer.check_skill_navigation_links(self.root).ok)
        links = ["[real](missing.md)", "![image](missing.png)", r"\\[real](missing.md)",
                 r"\![real](missing.md)", r"[escaped \] text](missing.md)",
                 "[outer [inner]](missing.md)", r"[ref\]]: missing.md",
                 "[![image](AGENTS.md)](missing.md)", "![outer [inner](AGENTS.md)](missing.png)",
                 "[ref]:\n  missing.md", "[real](\n  missing.md)"]
        for content in links:
            with self.subTest(link=content):
                self.write("README.md", content)
                self.assertFalse(analyzer.check_skill_navigation_links(self.root).ok)
        self.write("README.md", r"\[literal](missing.md)")
        self.assertEqual(self.cli().returncode, 0)

    def test_multiline_link_title_target_deletion(self):
        for title in ('"Title"', "'Title'", '(Title)'):
            for prefix in ('', '!'):
                for content in (f'{prefix}[guide](docs/guide.md\n  {title})',
                                f'{prefix}[guide](docs/guide.md {title}\n)',
                                f'{prefix}[guide](\n docs/guide.md\n {title}\n)',
                                f'{prefix}[guide](docs/guide.md\n)'):
                    with self.subTest(content=content):
                        target = self.write("docs/guide.md", "# Guide")
                        self.write("README.md", content)
                        self.assertTrue(analyzer.check_skill_navigation_links(self.root).ok)
                        target.unlink()
                        result = analyzer.check_skill_navigation_links(self.root)
                        self.assertFalse(result.ok, result.detail)
                        self.assertIn("docs/guide.md", result.detail)
        self.write("README.md", '[guide](missing.md\n  "Title")')
        self.assertEqual(self.cli().returncode, 1)
        for content in ('[guide](missing.md\n\n "Title")', '[guide](missing.md "Title"\n\n)'):
            self.write("README.md", content)
            self.assertTrue(analyzer.check_skill_navigation_links(self.root).ok)

    def test_example_and_optional_links_do_not_fail(self):
        self.write("README.md", '''[external](https://example.com/not-fetched) [anchor](#not-checked)
[private](.agents/artifacts/not-present.md)
<!-- [comment](missing.md) -->
`[code](missing.md)`
~~~md
[fenced](missing.md)
~~~
````md
```
[nested](missing.md)
````
    [indented](missing.md)
''')
        result = analyzer.check_skill_navigation_links(self.root)
        self.assertTrue(result.ok, result.detail)
        self.assertIn("1 private artifact", result.detail)

    def test_escaped_and_multiline_title_target_deletion(self):
        titles = (r'"Say \"hello\""', r"'It\'s a guide'", r'(Use \(a guide\))',
                  r'"Trailing slash\\"', '"Line one\n    line two"',
                  "'Line one\nline two'", '(Line one\nline two)',
                  '"Line one\\\nline two"', "'Line one\\\nline two'", '(Line one\\\nline two)')
        for title in titles:
            for prefix in ('', '!'):
                with self.subTest(title=title, prefix=prefix):
                    target = self.write("docs/guide.md", "# Guide")
                    self.write("README.md", f'{prefix}[guide](docs/guide.md {title})')
                    self.assertTrue(analyzer.check_skill_navigation_links(self.root).ok)
                    target.unlink()
                    self.assertFalse(analyzer.check_skill_navigation_links(self.root).ok)
        self.assertEqual(self.cli().returncode, 1)

    def test_blockquoted_fences_and_container_exit(self):
        for prefix in ('> ', '> > ', '  > '):
            for fence in ('```', '~~~', '````'):
                with self.subTest(prefix=prefix, fence=fence):
                    code = f'{prefix}{fence}md\n{prefix}[example](missing.md)\n{prefix}{fence}\n'
                    self.write("README.md", code)
                    self.assertTrue(analyzer.check_skill_navigation_links(self.root).ok)
                    self.write("README.md", code + f'{prefix}[real](missing.md)\n')
                    self.assertFalse(analyzer.check_skill_navigation_links(self.root).ok)
        for content in ('> ```md\n> [example](missing.md)\n\n[real](missing.md)',
                        '> > ~~~\n> > [example](missing.md)\n> [real](missing.md)'):
            self.write("README.md", content)
            self.assertFalse(analyzer.check_skill_navigation_links(self.root).ok)
        self.write("README.md", '> ```\n> [example](missing.md)\n> ```')
        self.assertEqual(self.cli().returncode, 0)

    def test_inline_code_escape_and_run_boundaries(self):
        active = (r'\`[guide](missing.md)\`', '``[guide](missing.md)`',
                  '`[guide](missing.md)``', '`unclosed\n\n[guide](missing.md)`',
                  '> paragraph\n    [guide](missing.md)')
        for content in active:
            with self.subTest(active=content):
                self.write("README.md", content)
                self.assertFalse(analyzer.check_skill_navigation_links(self.root).ok)
        inactive = ('`[example](missing.md)`', '`` `[example](missing.md)` ``',
                    r'\\`[example](missing.md)`', r'`[example](missing.md)\`',
                    r'\``[example](missing.md)`', '> `code\n[example](missing.md)`',
                    '> `code\nlazy\n> [example](missing.md)`')
        for content in inactive:
            with self.subTest(inactive=content):
                self.write("README.md", content)
                self.assertTrue(analyzer.check_skill_navigation_links(self.root).ok)
        self.write("README.md", r'\`[guide](missing.md)\`')
        self.assertEqual(self.cli().returncode, 1)

    def test_comments_preserve_link_boundaries(self):
        for content in ('[label]<!-- note -->(missing.md)',
                        '[label]<!-- note\ncontinued -->(missing.md)',
                        '[label]<!-- note -->\n(missing.md)',
                        '<!-- [example](missing.md) -->'):
            with self.subTest(nonlink=content):
                self.write("README.md", content)
                self.assertTrue(analyzer.check_skill_navigation_links(self.root).ok)
        self.write("README.md", '[label]<!-- note -->(missing.md)')
        self.assertEqual(self.cli().returncode, 0)
        for content in ('[label<!-- note -->](missing.md)',
                        '<!-- [example](ignored.md) -->\n[real](missing.md)',
                        '[real](missing.md)<!-- note -->'):
            with self.subTest(link=content):
                self.write("README.md", content)
                self.assertFalse(analyzer.check_skill_navigation_links(self.root).ok)
        prose = analyzer._markdown_prose('before<!-- one\ntwo -->after')
        self.assertEqual(prose.count('\n'), 1)
        self.assertNotIn('one', prose)
        self.assertNotIn('two', prose)

    def test_list_contained_link_paragraphs(self):
        paragraphs = ('- item\n\n    [guide](docs/guide.md)',
                      '* item\n\n    [guide](docs/guide.md)',
                      '+ item\n\n\t[guide](docs/guide.md)',
                      '1. item\n\n    [guide](docs/guide.md)',
                      '10) item\n\n    [guide](docs/guide.md)',
                      '- parent\n  - child\n\n      [guide](docs/guide.md)',
                      '> - item\n>\n>     [guide](docs/guide.md)',
                      '- item\n\n    [ref]: docs/guide.md\n\n    [guide][ref]')
        for content in paragraphs:
            with self.subTest(content=content):
                target = self.write('docs/guide.md', '# Guide')
                self.write('README.md', content)
                self.assertTrue(analyzer.check_skill_navigation_links(self.root).ok)
                target.unlink()
                self.assertFalse(analyzer.check_skill_navigation_links(self.root).ok)
        self.write('README.md', paragraphs[0])
        self.assertEqual(self.cli().returncode, 1)
        for content in ('- item\n\n      [example](missing.md)',
                        '1. item\n\n       [example](missing.md)',
                        '- item\n\n  ```md\n  [example](missing.md)\n  ```',
                        '- ```md\n  [example](missing.md)\n  ```',
                        '- ```md\n  > [example](missing.md)\n  ```',
                        '`code\n2. [example](missing.md)`',
                        '`code\n2) [example](missing.md)`',
                        '`code\n-\n[example](missing.md)`'):
            with self.subTest(code=content):
                self.write('README.md', content)
                self.assertTrue(analyzer.check_skill_navigation_links(self.root).ok)
        self.write('README.md', '- ```md\n  [example](ignored.md)\n\n[real](missing.md)')
        self.assertFalse(analyzer.check_skill_navigation_links(self.root).ok)

    def test_bad_skill_subfile_link_and_escape(self):
        self.write(".cursor/skills/cci-orchestration/tasks-reference.md", "[bad](missing.md)")
        self.assertFalse(analyzer.check_skill_navigation_links(self.root).ok)
        self.write(".cursor/skills/cci-orchestration/tasks-reference.md", "# Good")
        self.write("README.md", "[outside](../outside.md)")
        self.assertFalse(analyzer.check_skill_navigation_links(self.root).ok)

    def test_each_failure_reaches_cli_exit(self):
        p = self.root / "README.md"
        for path, content, label in [(self.skill, "# no metadata", "skill discovery metadata"),
                                     (p, "[bad](missing.md)", "skill navigation links"),
                                     (self.root / "AGENTS.md", "x" * 25001, "root instruction budget")]:
            before = path.read_text()
            path.write_text(content)
            result = self.cli()
            self.assertEqual(result.returncode, 1, result.stdout + result.stderr)
            self.assertIn("[FAIL] " + label, result.stdout)
            path.write_text(before)
        (self.root / ".claude/skills/cci-orchestration").unlink()
        result = self.cli()
        self.assertEqual(result.returncode, 1)
        self.assertIn("[FAIL] native skill links", result.stdout)

    def test_target_only_change_selects_gate(self):
        spec = next(c for c in pr_gate.CHECKS if c["name"] == "agent_tooling")
        self.assertFalse(pr_gate.selects(spec, []))
        for path in ("postman/docs/reference.md", "images/example.png", "NOTICE", ".claude/skills/example"):
            self.assertTrue(pr_gate.selects(spec, [path]), path)


if __name__ == "__main__":
    unittest.main()
