import { createElement } from 'lwc';
import GenericRecordPicker from 'c/genericRecordPicker';

describe('c-generic-record-picker', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const cmpInstance = createElement('c-generic-record-picker', {
            is: GenericRecordPicker
        });

        // Act
        document.body.appendChild(cmpInstance);
        const childCmp = cmpInstance.shadowRoot.querySelector('lightning-record-picker');
        const testVal = '123';
        childCmp.dispatchEvent(new CustomEvent('change', { 
            detail: { recordId: testVal }
        }));

        // Assert
        expect(cmpInstance.currentSelectedRecordId).toBe(testVal);

        cmpInstance.currentSelectedRecordId = testVal;
    });
});