erDiagram
    ExpressionSetConstraintObj { string ExpressionSetId }
    ProductConfigurationFlow { string OwnerId, OwnerId, ReferenceObjectId, ReferenceObjectId, ReferenceObjectId }
    ProductConfigFlowAssignment
    ProductConfigurationRule