erDiagram
    AttributeAdjustmentCondition { string AttributeBasedAdjRuleId, AttributeDefinitionId, ProductId }
    AttributeBasedAdjRule { string OwnerId, OwnerId }
    AttributeBasedAdjustment { string AttributeBasedAdjRuleId, PriceAdjustmentScheduleId, ProductId, ProductSellingModelId }
    AttributeDefinition
    BundleBasedAdjustment { string ParentProductId, ParentProductSellingModelId, PriceAdjustmentScheduleId }
    CostBook
    ContractItemPrice { string ContractId }
    CostBookEntry { string CostBookId, ProductId }
    PriceAdjustmentSchedule
    PriceAdjustmentTier { string PriceAdjustmentScheduleId }
    PriceBook2
    PriceBookEntry { string Pricebook2Id, Product2Id }
    PriceBookEntryDerivedPrice
    PriceRevisionPolicy
    AttributeAdjustmentCondition }o--|| AttributeBasedAdjRule : AttributeBasedAdjRuleId
    AttributeAdjustmentCondition }o--|| AttributeDefinition : AttributeDefinitionId
    AttributeBasedAdjustment }o--|| AttributeBasedAdjRule : AttributeBasedAdjRuleId
    AttributeBasedAdjustment }o--|| PriceAdjustmentSchedule : PriceAdjustmentScheduleId
    BundleBasedAdjustment }o--|| PriceAdjustmentSchedule : PriceAdjustmentScheduleId
    CostBookEntry ||--o{ CostBook : CostBookId
    PriceAdjustmentTier ||--o{ PriceAdjustmentSchedule : PriceAdjustmentScheduleId
    PriceBookEntry }o--|| PriceBook2 : Pricebook2Id