#!/usr/bin/env python
"""Scan the repo for every defect class in scripts/ai/defect_classes.yml.

This is Tier E of the pre-push gate (todo 080). It turns "sweep the class" from a
judgement call into a deterministic check.

Design rules inherited from the todo pack, each of which exists because it was
violated before:

  * A SKIP MUST NEVER READ AS A PASS. Every class reports executed / skipped /
    failed. A class that could not run is a non-zero exit, not silence.
  * The scan covers the WHOLE matching surface, not just changed hunks. PR #317's
    round-9 misses were in files the change never touched.
  * The interpreter is resolved explicitly. `python` on a dev box here is a pyenv
    shim without PyYAML; importing yaml under it raises ModuleNotFoundError and a
    naive caller reads the failure as "no findings".

Exit codes:
    0  every class executed, no findings
    1  findings (mechanical match, or a NEW baseline match)
    2  could not execute (bad registry, no usable interpreter) — never "clean"

Usage:
    python scripts/ai/defect_scan.py                  # scan everything
    python scripts/ai/defect_scan.py --class soql-missing-user-mode
    python scripts/ai/defect_scan.py --emit-baseline  # print allow_list YAML to pin
"""

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
REGISTRY = REPO_ROOT / "scripts" / "ai" / "defect_classes.yml"

# Directories never worth scanning: generated, vendored, or not our source.
PRUNE = {
    ".git", "node_modules", ".sfdx", ".harness", ".agents",
    "unpackaged/post_ux",  # auto-generated by assemble_and_deploy_ux
}


# The interpreter guard lives in _gate_interpreter so this script and
# pre_push_audit.py cannot drift apart on the one trap that matters most:
# `python` here is a pyenv shim without PyYAML, and a scan that dies on
# `import yaml` must never be read as "no findings".
sys.path.insert(0, str(Path(__file__).resolve().parent))

from _gate_interpreter import ensure_pyyaml  # noqa: E402

ensure_pyyaml(__file__)
import yaml  # noqa: E402  (import deferred until the interpreter is known good)


def _pruned(path: Path) -> bool:
    rel = path.relative_to(REPO_ROOT).as_posix()
    return any(rel == p or rel.startswith(p + "/") for p in PRUNE) or any(
        part in PRUNE for part in path.parts
    )


def _files_for(globs, exclude_globs=()):
    seen = set()
    for pattern in globs:
        for path in REPO_ROOT.glob(pattern):
            if path.is_file() and not _pruned(path):
                seen.add(path)
    for pattern in exclude_globs or ():
        for path in REPO_ROOT.glob(pattern):
            seen.discard(path)
    return sorted(seen)


_WS_RE = re.compile(r"[ \t\r\n]+")


def _blank_comments(text: str) -> str:
    """Replace //, /* */ and <!-- --> comment BODIES with spaces, preserving
    length and newlines so match offsets still map to the right line."""
    out = list(text)
    i, n = 0, len(text)
    while i < n:
        two = text[i:i + 2]
        if two == "//":
            j = text.find("\n", i)
            j = n if j == -1 else j
        elif two == "/*":
            j = text.find("*/", i + 2)
            j = n if j == -1 else j + 2
        elif text[i:i + 4] == "<!--":
            j = text.find("-->", i + 4)
            j = n if j == -1 else j + 3
        else:
            i += 1
            continue
        for k in range(i, j):
            if out[k] != "\n":
                out[k] = " "
        i = j
    return "".join(out)


def _norm(text: str) -> str:
    return re.sub(r"\s+", " ", text).strip()


def _key(rel_path: str, matched: str) -> str:
    """Allow-list key.

    Deliberately NOT line-number based — line numbers churn on every reformat,
    which would silently invalidate the whole baseline.

    Whitespace is stripped ENTIRELY rather than collapsed, because collapsing is
    not enough: Prettier rewrites `WHERE Id =:productId` to `WHERE Id = :productId`,
    so a baseline pinned before an Apex reformat stops matching afterwards and the
    whole allow-list silently reopens as fresh findings. Caught by running the
    todo-080 acceptance test against PR #317's head, where exactly this happened
    to five pinned queries. Case is preserved — `null` vs `NULL` must stay
    distinguishable."""
    # Precompiled and kept OUT of the f-string: before Python 3.12 an f-string
    # expression cannot contain a backslash, so inlining this regex is a
    # SyntaxError on 3.9 - which crashes the scan and, worse, looks like a
    # findings-exit rather than a did-not-run.
    return f"{rel_path}::{_WS_RE.sub('', matched)}"


def scan_class(cls):
    """Return (status, findings, error). status in {executed, skipped}."""
    detection = cls.get("detection")
    if detection == "review-prompt":
        return "prompt", [], None

    patterns = cls.get("patterns") or []
    if not patterns:
        return "skipped", [], "detection is mechanical/baseline but no patterns defined"

    try:
        compiled = [re.compile(p) for p in patterns]
    except re.error as exc:
        return "skipped", [], f"bad regex: {exc}"

    files = _files_for(cls.get("paths") or [], cls.get("exclude_paths") or [])
    if not files:
        return "executed", [], None

    allowed = {
        _key(entry["file"], entry["match"])
        for entry in (cls.get("allow_list") or [])
    }

    findings = []
    for path in files:
        rel = path.relative_to(REPO_ROOT).as_posix()
        try:
            text = path.read_text(encoding="utf-8", errors="replace")
        except OSError as exc:
            return "skipped", [], f"unreadable {rel}: {exc}"
        skip_comments = cls.get("ignore_comment_lines")

        # WHOLE-FILE scanning for classes whose construct spans lines. A
        # line-based scan cannot see them at all, and it fails SILENTLY - it
        # reports "ok" while being structurally incapable of matching, which is
        # the worst failure mode a gate has.
        #
        # This is not hypothetical here: `soql-missing-user-mode` requires the
        # closing `]`, and 265 of this repo's 370 SOQL literals span lines -
        # a share the Apex reformat on this very branch INCREASED, because
        # Prettier splits long queries. The flagship class was seeing 28% of its
        # own surface.
        if cls.get("multiline"):
            # Comment filtering has to survive whole-file mode too, or a class
            # about user-facing STRINGS starts firing on prose in comments —
            # which is what forced ignore_comment_lines to exist. Blank the
            # comment bodies rather than deleting them, so byte offsets (and
            # therefore reported line numbers) stay correct.
            scan_text = _blank_comments(text) if skip_comments else text
            for rx in compiled:
                for m in rx.finditer(scan_text):
                    if _key(rel, m.group(0)) in allowed:
                        continue
                    findings.append({
                        "file": rel,
                        "line": text.count("\n", 0, m.start()) + 1,
                        # FULL match, never truncated. --emit-baseline prints this
                        # verbatim as an allow_list key, so a display-truncated
                        # value would emit a baseline that cannot match its own
                        # findings — every query over the cut length would stay
                        # "unpinned" forever. Truncation happens at PRINT time.
                        "match": _norm(m.group(0)),
                    })
            continue

        for lineno, line in enumerate(text.splitlines(), 1):
            # Classes about USER-FACING STRINGS must not fire on prose in comments;
            # a comment saying "can return no rows" is documentation, not a claim
            # shown to anyone.
            if skip_comments and re.match(r"\s*(?://|\*|/\*|<!--|#)", line):
                continue
            for rx in compiled:
                m = rx.search(line)
                if not m:
                    continue
                if _key(rel, m.group(0)) in allowed:
                    continue
                findings.append(
                    {"file": rel, "line": lineno, "match": _norm(m.group(0))}
                )
                break
    return "executed", findings, None


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--class", dest="only", help="scan a single class id")
    ap.add_argument("--emit-baseline", action="store_true",
                    help="print allow_list YAML pinning current matches")
    ap.add_argument("--quiet", action="store_true", help="only print failures")
    ap.add_argument("--ack", action="append", default=[], metavar="CLASS_ID",
                    help="acknowledge a review-prompt class (repeatable). Without "
                         "this, unacknowledged prompts exit 2 — they are checklist "
                         "items that have not been done, not passes.")
    args = ap.parse_args()

    if not REGISTRY.exists():
        sys.stderr.write(f"FATAL: registry not found at {REGISTRY}\n")
        return 2
    try:
        registry = yaml.safe_load(REGISTRY.read_text(encoding="utf-8"))
    except yaml.YAMLError as exc:
        sys.stderr.write(f"FATAL: registry is not valid YAML: {exc}\n")
        return 2

    classes = registry.get("classes") or []
    if args.only:
        classes = [c for c in classes if c.get("id") == args.only]
        if not classes:
            sys.stderr.write(f"FATAL: no class with id {args.only!r}\n")
            return 2

    executed = skipped = prompts_acked = 0
    prompts_open = []
    acked = set(args.ack)
    total_findings = 0
    baseline_out = {}

    for cls in classes:
        cid = cls.get("id", "<unnamed>")
        status, findings, error = scan_class(cls)

        if status == "prompt":
            # A prompt that cannot affect the exit code is decoration. These were
            # counted, printed and then ignored — including two severity:blocker
            # classes — while three places in this repo stated they block until
            # acknowledged. They do now.
            if cid in acked:
                prompts_acked += 1
                if not args.quiet:
                    print(f"  ok      {cid}  (review prompt acknowledged)")
            else:
                prompts_open.append(cid)
                print(f"  PROMPT  {cid}  (manual checklist — not greppable, "
                      f"severity={cls.get('severity', '?')})")
            continue
        if status == "skipped":
            skipped += 1
            print(f"  SKIPPED {cid}  -- {error}")
            continue

        executed += 1
        if args.emit_baseline and findings:
            baseline_out[cid] = findings
            continue
        if findings:
            total_findings += len(findings)
            print(f"  FAIL    {cid}  ({len(findings)} finding(s), severity="
                  f"{cls.get('severity', '?')})")
            for f in findings[:20]:
                print(f"            {f['file']}:{f['line']}  {f['match'][:160]}")
            if len(findings) > 20:
                print(f"            … and {len(findings) - 20} more")
            print(f"            fix: {_norm(cls.get('remediation', '—'))}")
        elif not args.quiet:
            print(f"  ok      {cid}")

    if args.emit_baseline:
        print("\n# paste into the class's allow_list, adding a reason to each entry")
        for cid, findings in baseline_out.items():
            print(f"\n# --- {cid} ({len(findings)}) ---")
            print("    allow_list:")
            for f in findings:
                print(f"      - file: \"{f['file']}\"")
                escaped = f["match"].replace("\\", "\\\\").replace('"', '\\"')
                print(f'        match: "{escaped}"')
                print('        reason: "TODO"')
        return 0

    print(f"\nclasses: {executed} executed, "
          f"{prompts_acked + len(prompts_open)} manual-review "
          f"({prompts_acked} acknowledged, {len(prompts_open)} open), "
          f"{skipped} skipped")
    if skipped:
        print("SKIPPED CLASSES ARE FAILURES — a check that did not run is not a pass.")
        return 2
    if prompts_open:
        print("\nUNACKNOWLEDGED REVIEW PROMPTS — these are checklist items that\n"
              "have not been done. Confirm each, then re-run with:")
        for cid in prompts_open:
            print(f"    --ack {cid}")
        return 2
    if total_findings:
        print(f"{total_findings} finding(s).")
        return 1
    print("no findings.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
