#!/usr/bin/env python
"""Scan the repo for every defect class in scripts/ai/defect_classes.yml.

This is Tier E of the pre-push gate (todo 080). It turns "sweep the class" from a
judgement call into a deterministic check.

Design rules inherited from the todo pack, each of which exists because it was
violated before:

  * A SKIP MUST NEVER READ AS A PASS. Every class reports executed / skipped /
    failed. A class that could not run is a non-zero exit, not silence.
  * The scan covers the WHOLE matching surface, not just changed hunks. PR #317's
    round-9 misses were in files the change never touched.
  * The interpreter is resolved explicitly. `python` on a dev box here is a pyenv
    shim without PyYAML; importing yaml under it raises ModuleNotFoundError and a
    naive caller reads the failure as "no findings".

Exit codes:
    0  every class executed, no findings
    1  findings (mechanical match, or a NEW baseline match)
    2  could not execute (bad registry, no usable interpreter) — never "clean"

Usage:
    python scripts/ai/defect_scan.py                  # scan everything
    python scripts/ai/defect_scan.py --class soql-missing-user-mode
    python scripts/ai/defect_scan.py --emit-baseline  # print allow_list YAML to pin
"""

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
REGISTRY = REPO_ROOT / "scripts" / "ai" / "defect_classes.yml"

# Directories never worth scanning: generated, vendored, or not our source.
PRUNE = {
    ".git", "node_modules", ".sfdx", ".harness", ".agents",
    "unpackaged/post_ux",  # auto-generated by assemble_and_deploy_ux
}


# The interpreter guard lives in _gate_interpreter so this script and
# pre_push_audit.py cannot drift apart on the one trap that matters most:
# `python` here is a pyenv shim without PyYAML, and a scan that dies on
# `import yaml` must never be read as "no findings".
sys.path.insert(0, str(Path(__file__).resolve().parent))

from _gate_interpreter import ensure_pyyaml  # noqa: E402

ensure_pyyaml(__file__)
import yaml  # noqa: E402  (import deferred until the interpreter is known good)


def _pruned(path: Path) -> bool:
    rel = path.relative_to(REPO_ROOT).as_posix()
    return any(rel == p or rel.startswith(p + "/") for p in PRUNE) or any(
        part in PRUNE for part in path.parts
    )


def _files_for(globs, exclude_globs=()):
    seen = set()
    for pattern in globs:
        for path in REPO_ROOT.glob(pattern):
            if path.is_file() and not _pruned(path):
                seen.add(path)
    for pattern in exclude_globs or ():
        for path in REPO_ROOT.glob(pattern):
            seen.discard(path)
    return sorted(seen)


def _norm(text: str) -> str:
    return re.sub(r"\s+", " ", text).strip()


def _key(rel_path: str, matched: str) -> str:
    """Allow-list key.

    Deliberately NOT line-number based — line numbers churn on every reformat,
    which would silently invalidate the whole baseline.

    Whitespace is stripped ENTIRELY rather than collapsed, because collapsing is
    not enough: Prettier rewrites `WHERE Id =:productId` to `WHERE Id = :productId`,
    so a baseline pinned before an Apex reformat stops matching afterwards and the
    whole allow-list silently reopens as fresh findings. Caught by running the
    todo-080 acceptance test against PR #317's head, where exactly this happened
    to five pinned queries. Case is preserved — `null` vs `NULL` must stay
    distinguishable."""
    return f"{rel_path}::{re.sub(r'[ \t\r\n]+', '', matched)}"


def scan_class(cls):
    """Return (status, findings, error). status in {executed, skipped}."""
    detection = cls.get("detection")
    if detection == "review-prompt":
        return "prompt", [], None

    patterns = cls.get("patterns") or []
    if not patterns:
        return "skipped", [], "detection is mechanical/baseline but no patterns defined"

    try:
        compiled = [re.compile(p) for p in patterns]
    except re.error as exc:
        return "skipped", [], f"bad regex: {exc}"

    files = _files_for(cls.get("paths") or [], cls.get("exclude_paths") or [])
    if not files:
        return "executed", [], None

    allowed = {
        _key(entry["file"], entry["match"])
        for entry in (cls.get("allow_list") or [])
    }

    findings = []
    for path in files:
        rel = path.relative_to(REPO_ROOT).as_posix()
        try:
            text = path.read_text(encoding="utf-8", errors="replace")
        except OSError as exc:
            return "skipped", [], f"unreadable {rel}: {exc}"
        skip_comments = cls.get("ignore_comment_lines")
        for lineno, line in enumerate(text.splitlines(), 1):
            # Classes about USER-FACING STRINGS must not fire on prose in comments;
            # a comment saying "can return no rows" is documentation, not a claim
            # shown to anyone.
            if skip_comments and re.match(r"\s*(?://|\*|/\*|<!--|#)", line):
                continue
            for rx in compiled:
                m = rx.search(line)
                if not m:
                    continue
                if _key(rel, m.group(0)) in allowed:
                    continue
                findings.append(
                    {"file": rel, "line": lineno, "match": _norm(m.group(0))[:160]}
                )
                break
    return "executed", findings, None


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--class", dest="only", help="scan a single class id")
    ap.add_argument("--emit-baseline", action="store_true",
                    help="print allow_list YAML pinning current matches")
    ap.add_argument("--quiet", action="store_true", help="only print failures")
    args = ap.parse_args()

    if not REGISTRY.exists():
        sys.stderr.write(f"FATAL: registry not found at {REGISTRY}\n")
        return 2
    try:
        registry = yaml.safe_load(REGISTRY.read_text(encoding="utf-8"))
    except yaml.YAMLError as exc:
        sys.stderr.write(f"FATAL: registry is not valid YAML: {exc}\n")
        return 2

    classes = registry.get("classes") or []
    if args.only:
        classes = [c for c in classes if c.get("id") == args.only]
        if not classes:
            sys.stderr.write(f"FATAL: no class with id {args.only!r}\n")
            return 2

    executed = skipped = prompts = 0
    total_findings = 0
    baseline_out = {}

    for cls in classes:
        cid = cls.get("id", "<unnamed>")
        status, findings, error = scan_class(cls)

        if status == "prompt":
            prompts += 1
            if not args.quiet:
                print(f"  REVIEW  {cid}  (manual checklist — not greppable)")
            continue
        if status == "skipped":
            skipped += 1
            print(f"  SKIPPED {cid}  -- {error}")
            continue

        executed += 1
        if args.emit_baseline and findings:
            baseline_out[cid] = findings
            continue
        if findings:
            total_findings += len(findings)
            print(f"  FAIL    {cid}  ({len(findings)} finding(s), severity="
                  f"{cls.get('severity', '?')})")
            for f in findings[:20]:
                print(f"            {f['file']}:{f['line']}  {f['match']}")
            if len(findings) > 20:
                print(f"            … and {len(findings) - 20} more")
            print(f"            fix: {_norm(cls.get('remediation', '—'))}")
        elif not args.quiet:
            print(f"  ok      {cid}")

    if args.emit_baseline:
        print("\n# paste into the class's allow_list, adding a reason to each entry")
        for cid, findings in baseline_out.items():
            print(f"\n# --- {cid} ({len(findings)}) ---")
            print("    allow_list:")
            for f in findings:
                print(f"      - file: \"{f['file']}\"")
                escaped = f["match"].replace("\\", "\\\\").replace('"', '\\"')
                print(f'        match: "{escaped}"')
                print('        reason: "TODO"')
        return 0

    print(f"\nclasses: {executed} executed, {prompts} manual-review, {skipped} skipped")
    if skipped:
        print("SKIPPED CLASSES ARE FAILURES — a check that did not run is not a pass.")
        return 2
    if total_findings:
        print(f"{total_findings} finding(s).")
        return 1
    print("no findings.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
