#!/usr/bin/env python3
"""Generate a minimal, mechanically-accurate README.md for an SFDMU plan directory.

Derives the object table (Object, Operation, External ID, Records) and a file
listing straight from export.json + the plan's CSVs, reusing
check_plan_readme_consistency.py's own parsing (object_name/load_plan/csv_index/
csv_row_count) rather than re-deriving it — so the generated README is guaranteed
to pass that check, and stays the same defect class it isn't (see packs 160-163:
duplicated ad hoc SOQL/export.json parsing drifts from the canonical parser).

This intentionally does NOT attempt the narrative prose (flow integration, pass
architecture, portability notes) that hand-written plan READMEs carry — that
requires domain knowledge no script has. Regenerating overwrites only the
mechanical object table and file listing; hand-add narrative sections above/below
if the plan warrants it.

Usage:
  python scripts/ai/generate_plan_readme.py datasets/sfdmu/mfg/en-US/mfg-billing
  python scripts/ai/generate_plan_readme.py --all-missing   # every tracked plan with
                                                              # export.json and no README.md
"""
from __future__ import annotations

import argparse
import os
import subprocess
import sys

sys.path.insert(0, os.path.dirname(__file__))
from check_plan_readme_consistency import (  # noqa: E402
    REPO_ROOT,
    SFDMU_ROOT,
    csv_index,
    csv_row_count,
    load_plan,
)

TEMPLATE = """# {title} Data Plan

<!-- Generated by scripts/ai/generate_plan_readme.py from export.json + CSVs.
     Regenerate after changing this plan's objects/operations/externalIds rather
     than hand-editing the table below; add narrative sections separately. -->

## Objects

| # | Object | Operation | External ID | Records |
|---|--------|-----------|-------------|---------|
{rows}

## Files

```
{files}
```
"""


def root_counts(plan_dir: str) -> dict[str, int]:
    """name -> row count for the CSV directly in plan_dir (not an objectset_source
    override) — the same file pass 1 always reads regardless of useSeparatedCSVFiles."""
    out = {}
    for name, paths in csv_index(plan_dir).items():
        for p in paths:
            if os.path.dirname(os.path.abspath(p)) == os.path.abspath(plan_dir):
                out[name] = csv_row_count(p)
    return out


def generate(plan_dir: str) -> str:
    plan = load_plan(os.path.join(plan_dir, "export.json"))
    counts = root_counts(plan_dir)

    rows = []
    files = []
    for i, (name, variants) in enumerate(plan.items(), start=1):
        first = variants[0]
        op = first["operation"] or "—"
        ext_id = first["externalId"] or "—"
        n = counts.get(name)
        records = str(n) if n is not None else "—"
        rows.append(f"| {i} | {name} | {op} | {ext_id} | {records} |")
        if n is not None:
            files.append(f"{name}.csv".ljust(40) + f"# {n} record{'s' if n != 1 else ''}")

    return TEMPLATE.format(
        title=os.path.basename(plan_dir),
        rows="\n".join(rows),
        files="\n".join(files) if files else "(no CSVs — every object is Readonly or excluded)",
    )


def find_missing() -> list[str]:
    dirs = []
    for root, _d, filenames in os.walk(SFDMU_ROOT):
        if "export.json" in filenames and "README.md" not in filenames:
            dirs.append(root)
    return sorted(dirs)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("targets", nargs="*", help="Plan dirs to generate a README for")
    ap.add_argument("--all-missing", action="store_true", help="Generate for every tracked plan with export.json and no README.md")
    args = ap.parse_args()

    targets = args.targets
    if args.all_missing:
        targets = find_missing()
        # Only tracked plans — skip local/gitignored scratch dirs (e.g. datasets/sfdmu/test/).
        tracked = subprocess.run(
            ["git", "ls-files", "datasets/sfdmu"], cwd=REPO_ROOT, capture_output=True, text=True, check=True
        ).stdout.splitlines()
        tracked_dirs = {os.path.join(REPO_ROOT, os.path.dirname(f)) for f in tracked}
        targets = [t for t in targets if t in tracked_dirs]

    if not targets:
        print("No targets.", file=sys.stderr)
        return 1

    for t in targets:
        t = os.path.abspath(t)
        readme = os.path.join(t, "README.md")
        content = generate(t)
        with open(readme, "w", encoding="utf-8") as fh:
            fh.write(content)
        print(f"wrote {os.path.relpath(readme, REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
