#!/usr/bin/env python3
"""Generate a minimal, mechanically-accurate README.md for an SFDMU plan directory.

Derives the object table (Object, Pass, Operation, External ID, Records) and a
file listing straight from export.json + the plan's CSVs, reusing
check_plan_readme_consistency.py's own parsing (object_name/load_plan/csv_index/
csv_row_count) rather than re-deriving it — so the generated README is guaranteed
to pass that check, and stays the same defect class it isn't (see packs 160-163:
duplicated ad hoc SOQL/export.json parsing drifts from the canonical parser).

An object that carries a different operation/externalId per pass (Upsert in Pass
1, Update in Pass 2, say) gets one row per pass — the plan's own pass boundaries,
read straight off export.json's objectSets order, not folded into a single row
that would only show the first pass's behavior.

This intentionally does NOT attempt the narrative prose (flow integration, pass
architecture, portability notes) that hand-written plan READMEs carry — that
requires domain knowledge no script has. The generated table+listing lives
between two HTML-comment markers; regenerating an EXISTING README replaces only
that block and leaves everything outside it — narrative sections included —
untouched. A README with no markers (a legacy hand-written one, or one a prior
run of this script never touched) is left alone unless --force is passed, which
replaces the whole file and discards anything outside the block.

Usage:
  python scripts/ai/generate_plan_readme.py datasets/sfdmu/mfg/en-US/mfg-billing
  python scripts/ai/generate_plan_readme.py --all-missing   # every tracked plan with
                                                              # export.json and no README.md
  python scripts/ai/generate_plan_readme.py <plan_dir> --force  # replace a marker-less README wholesale
"""
from __future__ import annotations

import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from check_plan_readme_consistency import (  # noqa: E402
    REPO_ROOT,
    csv_index,
    csv_row_count,
    find_plan_dirs,
    load_export_data,
    load_plan,
    tracked_files,
)
from validate_sfdmu_v5_datasets import SFDMUValidator  # noqa: E402

BEGIN_MARKER = "<!-- generate_plan_readme:begin -->"
END_MARKER = "<!-- generate_plan_readme:end -->"

BLOCK_TEMPLATE = """{begin}
<!-- Generated by scripts/ai/generate_plan_readme.py from export.json + CSVs.
     Regenerate with the same command after changing this plan's objects,
     operations, or externalIds rather than hand-editing this block — content
     outside these markers (narrative sections) is preserved on regeneration. -->

## Objects

| # | Object | Pass | Operation | External ID | Records |
|---|--------|------|-----------|-------------|---------|
{rows}

## Files

```
{files}
```
{end}"""

FRESH_TEMPLATE = """# {title} Data Plan

{block}
"""


def resolve_pass_csv(plan_dir: str, csv_idx: dict, use_separated: bool, name: str, pass_no: int,
                      count_cache: dict | None = None):
    """(count, path-relative-to-plan_dir) for the CSV this pass actually reads,
    mirroring validate_sfdmu_v5_datasets.py's _objects_owing_root_csv rule: pass 1
    always reads the root CSV regardless of an object-set-1/ override or the flag;
    pass N>1 reads objectset_source/object-set-N/<name>.csv only when
    useSeparatedCSVFiles is true and that file exists, else falls back to root.
    Restricting to the root CSV unconditionally (the prior behavior) emitted `—`
    for an object sourced only from an objectset_source override, e.g.
    procedure-plans' ProcedurePlanOption.csv (object-set-2 only, no root file).

    This is a deliberately simpler read-only echo of that rule for display purposes,
    not a call into the validator itself — commit 50d7e383 changed exactly this rule
    (excluding pass-1 overrides from the coverage set) after it had already shipped
    once, so re-check this docstring against `_objects_owing_root_csv`'s current
    docstring whenever that method changes.

    `count_cache`, keyed by absolute CSV path: an object declared in two passes with
    no per-pass override (common — most objects only override the root in one pass)
    resolves to the same physical file twice; without the cache that file is
    re-scanned by csv_row_count() once per pass instead of once per distinct file."""
    def counted(p: str) -> int:
        if count_cache is None:
            return csv_row_count(p)
        if p not in count_cache:
            count_cache[p] = csv_row_count(p)
        return count_cache[p]

    by_abspath = {os.path.abspath(p): p for p in csv_idx.get(name, [])}
    if pass_no > 1 and use_separated:
        override = os.path.abspath(os.path.join(plan_dir, "objectset_source", f"object-set-{pass_no}", f"{name}.csv"))
        if override in by_abspath:
            p = by_abspath[override]
            return counted(p), os.path.relpath(p, plan_dir)
    root = os.path.abspath(os.path.join(plan_dir, f"{name}.csv"))
    if root in by_abspath:
        p = by_abspath[root]
        return counted(p), os.path.relpath(p, plan_dir)
    return None, None


def generate_block(plan_dir: str) -> str:
    export_json = os.path.join(plan_dir, "export.json")
    data = load_export_data(export_json)
    plan = load_plan(export_json, data=data)
    # JS truthiness, not plain Python bool() — SFDMU reads this the same way it reads
    # excluded/deleteOldData, where `[]`/`{}` are truthy in JS but falsy in Python
    # (see validate_sfdmu_v5_datasets.py's _is_js_truthy docstring).
    use_separated = SFDMUValidator._is_js_truthy(data.get("useSeparatedCSVFiles"))
    csv_idx = csv_index(plan_dir)

    rows = []
    files: dict[str, int] = {}
    count_cache: dict[str, int] = {}
    row_num = 0
    for name, variants in plan.items():
        for variant in variants:
            row_num += 1
            pass_no = variant["pass"]
            # SFDMU's actual default for an absent `operation` key is "Readonly"
            # (ScriptObject.ts's class-field default), not "unspecified" — rendering
            # "—" implied the plan declared nothing when it declared Readonly.
            op = variant["operation"] or "Readonly"
            ext_id = variant["externalId"] or "—"
            count, relpath = resolve_pass_csv(plan_dir, csv_idx, use_separated, name, pass_no, count_cache)
            records = str(count) if count is not None else "—"
            rows.append(f"| {row_num} | {name} | {pass_no} | {op} | {ext_id} | {records} |")
            if relpath is not None and relpath not in files:
                files[relpath] = count

    # A literal space precedes "#" so a path >= 40 chars (e.g. an objectset_source/
    # object-set-N/ override) still gets a separator — ljust alone pads only when
    # shorter, so a plain `+` concatenation ran the two together for long paths.
    file_lines = [f"{p.ljust(40)} # {n} record{'s' if n != 1 else ''}" for p, n in files.items()]
    return BLOCK_TEMPLATE.format(
        begin=BEGIN_MARKER,
        end=END_MARKER,
        rows="\n".join(rows),
        files="\n".join(file_lines) if file_lines else "(no CSVs — every object is Readonly or excluded)",
    )


def write_readme(plan_dir: str, force: bool = False) -> tuple[bool, str]:
    """Returns (wrote, message)."""
    readme = os.path.join(plan_dir, "README.md")
    block = generate_block(plan_dir)

    if not os.path.isfile(readme):
        content = FRESH_TEMPLATE.format(title=os.path.basename(plan_dir), block=block)
        with open(readme, "w", encoding="utf-8") as fh:
            fh.write(content)
        return True, f"wrote {os.path.relpath(readme, REPO_ROOT)} (new)"

    with open(readme, encoding="utf-8") as fh:
        existing = fh.read()

    begin_idx = existing.find(BEGIN_MARKER)
    end_idx = existing.find(END_MARKER)
    # end_idx > begin_idx, not just "both present" — a README with the markers out of
    # order (bad manual edit, bad merge) must fall through to --force/skip below rather
    # than crash trying to split a block boundary that doesn't actually exist.
    if begin_idx != -1 and end_idx > begin_idx:
        pre = existing[:begin_idx]
        post = existing[end_idx + len(END_MARKER):]
        content = pre + block + post
        with open(readme, "w", encoding="utf-8") as fh:
            fh.write(content)
        return True, f"wrote {os.path.relpath(readme, REPO_ROOT)} (regenerated marked block, narrative preserved)"

    if force:
        content = FRESH_TEMPLATE.format(title=os.path.basename(plan_dir), block=block)
        with open(readme, "w", encoding="utf-8") as fh:
            fh.write(content)
        return True, f"wrote {os.path.relpath(readme, REPO_ROOT)} (--force: replaced whole file, no markers found)"

    return False, (
        f"skip {os.path.relpath(readme, REPO_ROOT)} — has no generate_plan_readme markers; "
        "regenerating would discard hand-written content. Pass --force to replace it wholesale."
    )


def find_missing() -> list[str]:
    """Delegates to check_plan_readme_consistency's own discovery rather than
    re-walking datasets/sfdmu here — a second independent walk could silently
    diverge from it (e.g. an exclusion rule added to one and not the other)."""
    _with_readme, no_readme = find_plan_dirs([])
    return no_readme


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("targets", nargs="*", help="Plan dirs to generate/regenerate a README for")
    ap.add_argument("--all-missing", action="store_true", help="Generate for every tracked plan with export.json and no README.md")
    ap.add_argument("--force", action="store_true", help="Replace a marker-less existing README wholesale instead of skipping it")
    args = ap.parse_args()

    targets = args.targets
    if args.all_missing:
        targets = find_missing()
        # Only tracked plans — skip local/gitignored scratch dirs (e.g. datasets/sfdmu/test/).
        # Reuses check_plan_readme_consistency's own tracked_files() rather than a second,
        # independent git-tracked-ness check that could silently diverge from it.
        tracked_set = tracked_files([os.path.join(t, "export.json") for t in targets])
        targets = [t for t in targets if os.path.join(t, "export.json") in tracked_set]

    if not targets:
        print("No targets.", file=sys.stderr)
        return 1

    ok = True
    for t in targets:
        wrote, message = write_readme(os.path.abspath(t), force=args.force)
        print(message)
        ok = ok and wrote
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
