#!/usr/bin/env python3
"""Generate a minimal, mechanically-accurate README.md for an SFDMU plan directory.

Derives the object table (Object, Pass, Operation, External ID, Records) and a
file listing straight from export.json + the plan's CSVs, reusing
check_plan_readme_consistency.py's own parsing (object_name/load_plan/csv_index/
csv_row_count) rather than re-deriving it — so the generated README is guaranteed
to pass that check, and stays the same defect class it isn't (see packs 160-163:
duplicated ad hoc SOQL/export.json parsing drifts from the canonical parser).

An object that carries a different operation/externalId per pass (Upsert in Pass
1, Update in Pass 2, say) gets one row per pass — the plan's own pass boundaries,
read straight off export.json's objectSets order, not folded into a single row
that would only show the first pass's behavior.

This intentionally does NOT attempt the narrative prose (flow integration, pass
architecture, portability notes) that hand-written plan READMEs carry — that
requires domain knowledge no script has. The generated table+listing lives
between two HTML-comment markers; regenerating an EXISTING README replaces only
that block and leaves everything outside it — narrative sections included —
untouched. A README with no markers (a legacy hand-written one, or one a prior
run of this script never touched) is left alone unless --force is passed, which
replaces the whole file and discards anything outside the block.

Usage:
  python scripts/ai/generate_plan_readme.py datasets/sfdmu/mfg/en-US/mfg-billing
  python scripts/ai/generate_plan_readme.py --all-missing   # every tracked plan with
                                                              # export.json and no README.md
  python scripts/ai/generate_plan_readme.py <plan_dir> --force  # replace a marker-less README wholesale
"""
from __future__ import annotations

import argparse
import os
import subprocess
import sys

sys.path.insert(0, os.path.dirname(__file__))
from check_plan_readme_consistency import (  # noqa: E402
    REPO_ROOT,
    SFDMU_ROOT,
    csv_index,
    csv_row_count,
    load_plan,
)

BEGIN_MARKER = "<!-- generate_plan_readme:begin -->"
END_MARKER = "<!-- generate_plan_readme:end -->"

BLOCK_TEMPLATE = """{begin}
<!-- Generated by scripts/ai/generate_plan_readme.py from export.json + CSVs.
     Regenerate with the same command after changing this plan's objects,
     operations, or externalIds rather than hand-editing this block — content
     outside these markers (narrative sections) is preserved on regeneration. -->

## Objects

| # | Object | Pass | Operation | External ID | Records |
|---|--------|------|-----------|-------------|---------|
{rows}

## Files

```
{files}
```
{end}"""

FRESH_TEMPLATE = """# {title} Data Plan

{block}
"""


def root_counts(plan_dir: str) -> dict[str, int]:
    """name -> row count for the CSV directly in plan_dir (not an objectset_source
    override) — the same file pass 1 always reads regardless of useSeparatedCSVFiles."""
    out = {}
    for name, paths in csv_index(plan_dir).items():
        for p in paths:
            if os.path.dirname(os.path.abspath(p)) == os.path.abspath(plan_dir):
                out[name] = csv_row_count(p)
    return out


def generate_block(plan_dir: str) -> str:
    plan = load_plan(os.path.join(plan_dir, "export.json"))
    counts = root_counts(plan_dir)

    rows = []
    files = []
    row_num = 0
    for name, variants in plan.items():
        n = counts.get(name)
        for pass_no, variant in enumerate(variants, start=1):
            row_num += 1
            op = variant["operation"] or "—"
            ext_id = variant["externalId"] or "—"
            records = str(n) if n is not None else "—"
            rows.append(f"| {row_num} | {name} | {pass_no} | {op} | {ext_id} | {records} |")
        if n is not None:
            files.append(f"{name}.csv".ljust(40) + f"# {n} record{'s' if n != 1 else ''}")

    return BLOCK_TEMPLATE.format(
        begin=BEGIN_MARKER,
        end=END_MARKER,
        rows="\n".join(rows),
        files="\n".join(files) if files else "(no CSVs — every object is Readonly or excluded)",
    )


def write_readme(plan_dir: str, force: bool = False) -> tuple[bool, str]:
    """Returns (wrote, message)."""
    readme = os.path.join(plan_dir, "README.md")
    block = generate_block(plan_dir)

    if not os.path.isfile(readme):
        content = FRESH_TEMPLATE.format(title=os.path.basename(plan_dir), block=block)
        with open(readme, "w", encoding="utf-8") as fh:
            fh.write(content)
        return True, f"wrote {os.path.relpath(readme, REPO_ROOT)} (new)"

    with open(readme, encoding="utf-8") as fh:
        existing = fh.read()

    if BEGIN_MARKER in existing and END_MARKER in existing:
        pre, rest = existing.split(BEGIN_MARKER, 1)
        _, post = rest.split(END_MARKER, 1)
        content = pre + block + post
        with open(readme, "w", encoding="utf-8") as fh:
            fh.write(content)
        return True, f"wrote {os.path.relpath(readme, REPO_ROOT)} (regenerated marked block, narrative preserved)"

    if force:
        content = FRESH_TEMPLATE.format(title=os.path.basename(plan_dir), block=block)
        with open(readme, "w", encoding="utf-8") as fh:
            fh.write(content)
        return True, f"wrote {os.path.relpath(readme, REPO_ROOT)} (--force: replaced whole file, no markers found)"

    return False, (
        f"skip {os.path.relpath(readme, REPO_ROOT)} — has no generate_plan_readme markers; "
        "regenerating would discard hand-written content. Pass --force to replace it wholesale."
    )


def find_missing() -> list[str]:
    dirs = []
    for root, _d, filenames in os.walk(SFDMU_ROOT):
        if "export.json" in filenames and "README.md" not in filenames:
            dirs.append(root)
    return sorted(dirs)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("targets", nargs="*", help="Plan dirs to generate/regenerate a README for")
    ap.add_argument("--all-missing", action="store_true", help="Generate for every tracked plan with export.json and no README.md")
    ap.add_argument("--force", action="store_true", help="Replace a marker-less existing README wholesale instead of skipping it")
    args = ap.parse_args()

    targets = args.targets
    if args.all_missing:
        targets = find_missing()
        # Only tracked plans — skip local/gitignored scratch dirs (e.g. datasets/sfdmu/test/).
        tracked = subprocess.run(
            ["git", "ls-files", "datasets/sfdmu"], cwd=REPO_ROOT, capture_output=True, text=True, check=True
        ).stdout.splitlines()
        tracked_dirs = {os.path.join(REPO_ROOT, os.path.dirname(f)) for f in tracked}
        targets = [t for t in targets if t in tracked_dirs]

    if not targets:
        print("No targets.", file=sys.stderr)
        return 1

    ok = True
    for t in targets:
        wrote, message = write_readme(os.path.abspath(t), force=args.force)
        print(message)
        ok = ok and wrote
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
