#!/usr/bin/env python3
"""Pure payload-shaping for Place Sales Transaction ramp operations.

Part of the self-contained ``scripts/ramp_deals/`` toolkit (imports nothing from
``tasks/``). Transport-agnostic and dependency-free: every function takes plain
values and returns a plain dict — the JSON body a caller POSTs to
``/connect/rev/sales-transaction/actions/place`` or ``…/actions/clone``. Nothing
here opens a socket, so it is fully unit-testable offline.

The graph shape (``graph.records[]`` with ``referenceId`` + ``record.attributes
{type, method[, id]}`` and ``@{ref.id}`` parent references) is the one verified
live in ``scripts/build_quote_to_asset.py`` and against the 264 org; the
``groupRampAction`` enum and the create-first-segment body are verbatim from
``DG/connect_requests_group_ramp_action_input.htm.md`` (PLAN.md §4.1).

Field legality (createable/updateable) is the live 264 describe in
``probe-264/E9-ramp-field-summary.md``. The genuinely-derived fields that the API
rejects on write are denied here so a caller cannot smuggle them in:

  * QuoteLineItem: ``EndQuantity``, ``NetUnitPrice``, ``TotalPrice``,
    ``RampIdentifier``, ``SegmentIdentifier`` are read-only (system-generated /
    calculated). ``RampIdentifier``/``SegmentIdentifier`` are generated by the
    ramp action itself — setting them is DO-NOT #6.
  * Quote: ``GrandTotal``, ``TotalPrice``, ``CalculationStatus``, ``QuoteNumber``
    are read-only.
"""

from __future__ import annotations

from typing import Any, Dict, List, Optional

from . import API_VERSION

# ``groupRampAction`` enum — DG/apex_enum_RevSalesTrxn_GroupRampActionEnum.
GROUP_RAMP_ACTIONS = frozenset({
    "EditGroup",
    "EditRampSchedule",
    "AddProducts",
    "DeleteProducts",
    "DeleteSegment",
    "ConvertToNonRampedGroup",
})

# Fields the Place Sales Transaction API rejects on write (derived / generated).
# Deny-lists, per live 264 describe (createable=False or generated by the action).
QUOTE_LINE_ITEM_READONLY = frozenset({
    "EndQuantity", "NetUnitPrice", "TotalPrice",
    "RampIdentifier", "SegmentIdentifier",
})
QUOTE_READONLY = frozenset({
    "GrandTotal", "TotalPrice", "CalculationStatus", "QuoteNumber",
})

PLACE_PATH = f"/services/data/{API_VERSION}/connect/rev/sales-transaction/actions/place"
CLONE_PATH = f"/services/data/{API_VERSION}/connect/rev/sales-transaction/actions/clone"


class PayloadError(ValueError):
    """A payload that would be rejected by the API — caught before the call."""


def _record(ref_id: str, sobject_type: str, method: str,
            fields: Optional[Dict[str, Any]] = None,
            record_id: Optional[str] = None) -> dict:
    """One ``graph.records[]`` entry.

    ``attributes`` carries ``type`` + ``method`` (+ ``id`` for PATCH). The
    remaining fields sit as siblings of ``attributes`` inside ``record`` — the
    shape build_quote_to_asset.py uses and the org accepts (NOT nested under a
    ``fields`` key).
    """
    attributes: Dict[str, Any] = {"type": sobject_type, "method": method}
    if method == "PATCH":
        if not record_id:
            raise PayloadError(f"PATCH on {sobject_type} requires a record id")
        attributes["id"] = record_id
    record: Dict[str, Any] = {"attributes": attributes}
    if fields:
        record.update(fields)
    return {"referenceId": ref_id, "record": record}


def _reject_readonly(fields: Dict[str, Any], deny: frozenset, obj: str) -> None:
    bad = sorted(set(fields) & deny)
    if bad:
        raise PayloadError(
            f"{obj}: {bad} are read-only / system-generated and are rejected on "
            "write (see E9-ramp-field-summary.md). Do not set them."
        )


def build_place_create(
    *,
    account_id: str,
    lines: List[dict],
    opportunity_id: Optional[str] = None,
    pricebook_id: Optional[str] = None,
    currency: Optional[str] = None,
    quote_name: str = "Ramped Quote",
    start_date: Optional[str] = None,
    group_name: str = "Segment 1",
    graph_id: str = "createRampQuote",
    pricing_pref: str = "System",
) -> dict:
    """Build the initial ``place`` body: Quote + one QuoteLineGroup + lines.

    Creates the transaction shell that a subsequent ``EditGroup`` converts into
    the first ramp segment. All records are ``POST`` (create); lines reference the
    quote via ``@{refQuote.id}`` and the group via ``@{refGroup.id}``.

    Each entry in ``lines`` is a plain dict of writable QuoteLineItem fields
    (``Product2Id``, ``PricebookEntryId``, ``UnitPrice``, ``Quantity``,
    ``StartDate``, ``EndDate``, …). ``QuoteId`` / ``QuoteLineGroupId`` are set
    here — do not include them. Read-only fields are rejected.
    """
    if not account_id:
        raise PayloadError("account_id is required")
    if not lines:
        raise PayloadError("at least one line is required")

    quote_fields: Dict[str, Any] = {
        "Name": quote_name,
        "QuoteAccountId": account_id,
        "Status": "Draft",
    }
    if opportunity_id:
        quote_fields["OpportunityId"] = opportunity_id
    if pricebook_id:
        quote_fields["Pricebook2Id"] = pricebook_id
    if currency:
        quote_fields["CurrencyIsoCode"] = currency
    if start_date:
        quote_fields["StartDate"] = start_date
    _reject_readonly(quote_fields, QUOTE_READONLY, "Quote")

    records = [_record("refQuote", "Quote", "POST", quote_fields)]

    group_fields: Dict[str, Any] = {
        "QuoteId": "@{refQuote.id}",
        "Name": group_name,
        # A plain (non-ramped) group at create; EditGroup flips IsRamped later.
        "Type": "CPQQuoteGroup",
    }
    records.append(_record("refGroup", "QuoteLineGroup", "POST", group_fields))

    for i, raw in enumerate(lines):
        if not isinstance(raw, dict):
            raise PayloadError(f"line {i} must be a dict, got {type(raw).__name__}")
        _reject_readonly(raw, QUOTE_LINE_ITEM_READONLY, f"line {i} (QuoteLineItem)")
        if "QuoteId" in raw or "QuoteLineGroupId" in raw:
            raise PayloadError(
                f"line {i}: do not set QuoteId/QuoteLineGroupId — the builder wires "
                "them to the graph references"
            )
        fields = dict(raw)
        fields["QuoteId"] = "@{refQuote.id}"
        fields["QuoteLineGroupId"] = "@{refGroup.id}"
        records.append(_record(f"refLine{i}", "QuoteLineItem", "POST", fields))

    return {
        "pricingPref": pricing_pref,
        "graph": {"graphId": graph_id, "records": records},
    }


def build_edit_group(
    *,
    quote_id: str,
    group_id: str,
    start_date: str,
    end_date: str,
    segment_type: str,
    sort_order: int = 1,
    graph_id: str = "editGroupRamp",
    pricing_pref: str = "System",
) -> dict:
    """Build the ``EditGroup`` body — convert a group into the first ramp segment.

    This is the one-and-only ``EditGroup`` per schedule: it PATCHes the Quote and
    the QuoteLineGroup, setting ``IsRamped=true`` + ``SegmentType`` + dates +
    ``SortOrder``. The action generates ``RampIdentifier``/``SegmentIdentifier`` on
    the group's lines — those are never set by the caller.
    """
    # Local import to avoid a hard dependency cycle at module import.
    from ._schedule import SEGMENT_TYPES
    if segment_type not in SEGMENT_TYPES:
        raise PayloadError(
            f"segment_type {segment_type!r} not in {sorted(SEGMENT_TYPES)} "
            "(the trial value is 'FreeTrial', not 'Trial')"
        )
    records = [
        _record("refQuote", "Quote", "PATCH", record_id=quote_id),
        _record("refGroup", "QuoteLineGroup", "PATCH", {
            "StartDate": start_date,
            "EndDate": end_date,
            "SortOrder": sort_order,
            "IsRamped": True,
            "SegmentType": segment_type,
        }, record_id=group_id),
    ]
    return _group_ramp_body("EditGroup", records, graph_id, pricing_pref)


def build_clone_segment(
    *,
    quote_id: str,
    last_segment_group_id: str,
    line_scope: str = "AllLines",
) -> dict:
    """Build the ``clone`` body that adds the next segment.

    Only the **last** segment can be cloned; ``recordIds`` accepts a single id
    only. Clone assigns the new segment's dates automatically. ``line_scope``:
    ``AllLines`` carries non-ramped lines forward, ``RampedLinesOnly`` drops them
    (the one-time-product lever).
    """
    if line_scope not in ("AllLines", "RampedLinesOnly"):
        raise PayloadError(
            f"line_scope {line_scope!r} must be 'AllLines' or 'RampedLinesOnly'"
        )
    return {
        "recordIds": [last_segment_group_id],
        "salesTransactionId": quote_id,
        "options": {"lineScope": line_scope},
    }


def build_group_ramp_action(
    action: str,
    *,
    records: List[dict],
    graph_id: str = "groupRampAction",
    pricing_pref: str = "System",
) -> dict:
    """Build a generic ``groupRampAction`` body for the remaining verbs.

    For ``AddProducts`` / ``DeleteProducts`` / ``DeleteSegment`` /
    ``EditRampSchedule`` / ``ConvertToNonRampedGroup``. ``records`` is the caller-
    shaped graph records list; use ``make_record`` to build entries so read-only
    fields are rejected consistently. ``EditGroup`` has its own dedicated builder.
    """
    if action == "EditGroup":
        raise PayloadError("use build_edit_group() for EditGroup")
    return _group_ramp_body(action, records, graph_id, pricing_pref)


def make_record(ref_id: str, sobject_type: str, method: str,
                fields: Optional[Dict[str, Any]] = None,
                record_id: Optional[str] = None) -> dict:
    """Public record builder with read-only-field rejection for the ramp objects."""
    if fields:
        if sobject_type == "QuoteLineItem":
            _reject_readonly(fields, QUOTE_LINE_ITEM_READONLY, "QuoteLineItem")
        elif sobject_type == "Quote":
            _reject_readonly(fields, QUOTE_READONLY, "Quote")
    return _record(ref_id, sobject_type, method, fields, record_id)


def _group_ramp_body(action: str, records: List[dict], graph_id: str,
                     pricing_pref: str) -> dict:
    if action not in GROUP_RAMP_ACTIONS:
        raise PayloadError(
            f"groupRampAction {action!r} not in {sorted(GROUP_RAMP_ACTIONS)}"
        )
    if not records:
        raise PayloadError(f"{action}: graph.records cannot be empty")
    return {
        "groupRampAction": action,
        "pricingPref": pricing_pref,
        "graph": {"graphId": graph_id, "records": records},
    }
